[package]
name = "crypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3", features = ['derive'] }
chacha20poly1305 = "0.9"
rand = "0.8"
thiserror = "1.0"
